modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/Barista/issues"
logoFile="logo.png"

[[mods]]
modId="barista"
version="${file.jarVersion}"
displayName="Barista"
authors="Ewy"
description=""

[[dependencies.barista]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="CLIENT"

[[dependencies.barista]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="CLIENT"