modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/Barista/issues"
logoFile="logo.png"

[[mods]]
modId="barista"
version="${file.jarVersion}"
displayName="Barista"
authors="Ewy"
description=""

[[dependencies.barista]]
modId="forge"
mandatory=true
versionRange="[32,)"
ordering="NONE"
side="CLIENT"

[[dependencies.barista]]
modId="minecraft"
mandatory=true
versionRange="[1.16.1, 1.17)"
ordering="NONE"
side="CLIENT"