modLoader="javafml"
loaderVersion="[38,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/Barista/issues"
logoFile="logo.png"

[[mods]]
modId="barista"
version="${file.jarVersion}"
displayName="Barista"
authors="Ewy"
description=""

[[dependencies.barista]]
modId="forge"
mandatory=true
versionRange="[38,)"
ordering="NONE"
side="CLIENT"

[[dependencies.barista]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="CLIENT"