plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
    id 'maven-publish'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

base {
    archivesName = project.MOD_NAME
}
version = project.MC_VERSION_GENERAL + "-" + project.VERSION + "-" + project.MOD_LOADER
group = project.MAVEN_GROUP

repositories {
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.terraformersmc.com/" }
    maven { url = "https://maven.gegy.dev" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.MC_VERSION}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${project.LOADER_VERSION}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.FABRIC_VERSION}"

    includeFabricApiModule "fabric-key-binding-api-v1"
    includeFabricApiModule "fabric-lifecycle-events-v1"

    modImplementation "com.terraformersmc:modmenu:${project.MODMENU_VERSION}"

    /*modRuntimeOnly ("supercoder79:databreaker:${project.DATABREAKER_VERSION}") {
        exclude module: "fabric-loader"
    }*/
}

def includeFabricApiModule(String moduleName) {
    Object dependency = fabricApi.module(moduleName, project.FABRIC_VERSION)
    dependencies.modImplementation(dependency)
    dependencies.include(dependency)
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {

    it.options.encoding = "UTF-8"
    def targetVersion = 21

    if (JavaVersion.current().isJava9Compatible()) {
        it.options.release = targetVersion
    }
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }
}

loom {
    accessWidenerPath = file("src/main/resources/barista.accesswidener")
}

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    if (project.hasProperty('CF_API_KEY')){
        apiToken = project.getProperty('CF_API_KEY')
    }

    def mainFile = upload(project.PROJECT_ID, jar)
    mainFile.releaseType = "${RELEASE_TYPE}"
    mainFile.addModLoader "${MOD_LOADER}"
    mainFile.addGameVersion "${MC_VERSION}"
    mainFile.addJavaVersion "${JAVA_VERSION}"
    mainFile.addEnvironment('Client', 'Server')

    mainFile.changelog = file("$project.rootDir/CHANGELOG.md")
    mainFile.changelogType = 'markdown'

    mainFile.displayName = "${MOD_NAME}-${MC_VERSION_GENERAL}-${VERSION}-${MOD_LOADER}.jar"
}