# Fabric Properties
MC_VERSION=26.2
MC_VERSION_GENERAL=26.2
LOADER_VERSION=0.19.3
JAVA_VERSION=Java 25

# Mod Properties
VERSION=1.4.0
MAVEN_GROUP=com.ewyboy
MOD_NAME=Barista
MOD_ID=barista
MOD_LOADER=Fabric

# Dependencies
FABRIC_VERSION=0.156.0+26.2

# Curse Forge
PROJECT_ID=552324
RELEASE_TYPE=release