# Fabric Properties
MC_VERSION=1.21.1
MC_VERSION_GENERAL=1.21.1
LOADER_VERSION=0.16.14
JAVA_VERSION=Java 21

# Mod Properties
VERSION=1.1.2
MAVEN_GROUP=com.ewyboy
MOD_NAME=Barista
MOD_ID=barista
MOD_LOADER=Fabric

# Dependencies
FABRIC_VERSION=0.116.0+1.21.1
MODMENU_VERSION=11.0.3
CLOTH_CONFIG_VERSION=15.0.140

# Curse Forge
PROJECT_ID=552324
RELEASE_TYPE=release