modLoader="javafml"
loaderVersion="${LOADER_VERSION_RANGE}"
license="${LICENSE}"
issueTrackerURL="https://github.com/EwyBoy/Barista/issues"
logoFile="logo.png"

[[mods]]
modId="${MODID}"
version="${VERSION}"
displayName="${MODNAME}"
authors="${AUTHOR}"
description="${DESCRIPTION}"

[[dependencies.${MODID}]]
modId="neoforge"
type="required"
versionRange="${NEO_VERSION_RANGE}"
ordering="NONE"
side="CLIENT"

[[dependencies.${MODID}]]
modId="minecraft"
type="required"
versionRange="${MC_VERSION_RANGE}"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="mixins.barista.json"
