#This is an String value
stringValue = "YEP"
#This is a Boolean value
booleanValue = false
#This is a List of Strings
listValue = []

#YEP
[more_properties]
	#This is an Integer value
	#Range: 0 ~ 10
	int_Value = 0
	#This is a Double value
	#Range: 0.0 ~ 10.0
	doubleValue = 0.0
	#This is a Long value
	#Range: 0 ~ 10
	longValue = 0
	#This is an Enum value
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
	enumValue = "BLACK"

