
plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
}

version = "${MC_VERSION}-${VERSION}"
group = "com.ewyboy.${MODID}"
base {
    archivesName = MODNAME
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "${NEO_VERSION}"

    parchment {
        mappingsVersion = "${PARCHMENT_MAPPINGS_VERSION}"
        minecraftVersion = "${PARCHMENT_MINECRAFT_VERSION}"
    }

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        data {
            data()

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', "${MODID}", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            if (javaToolchains.launcherFor(java.toolchain).map { it.metadata.vendor }.getOrElse('').contains('JetBrains')) {
                jvmArguments.addAll('-XX:+IgnoreUnrecognizedVMOptions', '-XX:+AllowEnhancedClassRedefinition')
            }

            jvmArgument '-Xmx4G'
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // multi mod projects should define one per mod
        "${MODID}" {
            sourceSet(sourceSets.main)
        }
    }
}
// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {

}

jar {
    manifest {
        attributes([
                "Specification-Title"     : MODNAME,
                "Specification-Vendor"    : AUTHOR,
                "Specification-Version"   : MC_VERSION,
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : VERSION,
                "Implementation-Vendor"   : AUTHOR,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    if (project.hasProperty('CF_API_KEY')) {
        apiToken = project.getProperty('CF_API_KEY')
    }

    def mainFile = upload(project.PROJECT_ID, jar)
    mainFile.releaseType = "${RELEASE_TYPE}"
    mainFile.addModLoader "${MOD_LOADER}"
    mainFile.addGameVersion "${MC_VERSION}"
    mainFile.addJavaVersion "${JAVA_VERSION}"
    mainFile.addEnvironment('Client', 'Server')

    mainFile.changelog = file("$project.rootDir/CHANGELOG.md")
    mainFile.changelogType = 'markdown'

    mainFile.displayName = "${MODNAME}-${MC_VERSION_GENERAL}-${VERSION}-${MOD_LOADER}.jar"
}