# Mod Info
VERSION=1.1.2
AUTHOR=Ewy
MODNAME=Barista
MODID=barista

# Dependencies
MC_VERSION=1.21.1
MC_VERSION_GENERAL=1.21.1
NEO_VERSION=21.1.227
JAVA_VERSION=Java 21
MOD_LOADER=NeoForge

# Mappings
PARCHMENT_MINECRAFT_VERSION=1.21.1
PARCHMENT_MAPPINGS_VERSION=2024.11.17

# Curse Forge
PROJECT_ID=552324
RELEASE_TYPE=release